USE [Diablo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE view [dbo].[APP_MESSAGE] ( [MSG_SEQ_NO], [CUS_NO], [MSG_TYPE], [OS_TYPE], [REMARK], [NEW_CODE], [NEW_DATE], [PRO_CODE], [RES_CODE], [Tag], [TITLE], [GPS_X], [GPS_Y] )  as select  [MSG_SEQ_NO], [CUS_NO], [MSG_TYPE], [OS_TYPE], [REMARK], [NEW_CODE], [NEW_DATE], [PRO_CODE], [RES_CODE], [Tag], [TITLE], [GPS_X], [GPS_Y]  from [dbo].[APP_MESSAGE_root] 
GO
